spring:
  application:
    name: authentification
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/myauthdb
    username: myauth
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: sialed
      password: 1234
    jwt:
      token:
        secret-key: mon-secret
